# Generated by Django 3.2.9 on 2022-10-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=21)),
                ('frequency', models.IntegerField(default=0)),
                ('ngram_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
